import unittest
import warnings

from base_tests import BaseTests, SameStringsMixin
from fpdf import FPDF

from mobile_strings_converter import DEFAULT_LOCALE, Catalog, Entry, parse, serialize
from mobile_strings_converter.converter import convert_strings


class TestToPdf(SameStringsMixin, BaseTests.ConvertToTest):
    def setUp(self):
        super().setUp()
        self.file_name = "strings.pdf"

    def test_converter_lists_unsupported_strings(self):
        errors_filepath = self.output_dir / "strings-errors.txt"

        # The file is overwritten on each conversion
        for _ in range(2):
            convert_strings(self.input_filepath_android, self.output_filepath)

        errors = errors_filepath.read_text(encoding="utf-8").splitlines()
        self.assertIn("මගේ යෙදුම භුක්ති විඳින්න not supported", errors)
        self.assertEqual(len(errors), len(set(errors)))


class TestFromPdf(BaseTests.ConvertFromTest):
    def setUp(self):
        super().setUp()
        self.file_name = "strings.pdf"


class TestPdfContent(unittest.TestCase):
    def test_round_trip(self):
        catalog = Catalog(
            [Entry("hello", {DEFAULT_LOCALE: "Hello\nWorld", "es": "Hola"})]
        )

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            data = serialize(catalog, ".pdf")

        self.assertEqual(catalog, parse(data, ".pdf"))

    def test_pdf_without_embedded_strings(self):
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("helvetica")
        pdf.cell(text="NAME VALUE")

        with self.assertRaisesRegex(
            ValueError, "generated by mobile-strings-converter"
        ):
            parse(bytes(pdf.output()), ".pdf")

    def test_invalid_file(self):
        with self.assertRaises(ValueError):
            parse(b"not a pdf", ".pdf")


if __name__ == "__main__":
    unittest.main()
